# Generated by Django 5.0 on 2023-12-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='uantity',
            new_name='quantity',
        ),
    ]
